# Generated by Django 3.0.3 on 2020-03-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.inventory')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=5000)),
                ('total_no', models.IntegerField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
