# Generated by Django 3.0.3 on 2020-04-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Need Restocking', 'Need Restocking'), ('SOLD', 'SOLD')], default='SOLD', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_no',
            field=models.IntegerField(),
        ),
    ]
