# Generated by Django 3.0.3 on 2020-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
