# Generated by Django 3.0.3 on 2020-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200402_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Need Restocking', 'Need Restocking'), ('SOLD', 'SOLD')], default='Available', max_length=50),
        ),
    ]
